- name: Reset MySQL root and enable remote access (RHEL 9)
  hosts: mysql
  become: yes

  vars:
    mysql_root_password: RoboShop@1

  tasks:

    - name: Install PyMySQL
      ansible.builtin.dnf:
        name: python3-PyMySQL
        state: present

    - name: Stop MySQL
      ansible.builtin.service:
        name: mysqld
        state: stopped
        ignore_errors: yes

    - name: Start MySQL in skip-grant-tables mode
      ansible.builtin.shell: |
        mkdir -p /var/run/mysqld
        chown mysql:mysql /var/run/mysqld
        mysqld --skip-grant-tables --skip-networking &
      async: 30
      poll: 0

    - name: Wait for MySQL socket (RHEL 9 path)
      ansible.builtin.wait_for:
        path: /var/run/mysqld/mysqld.sock
        timeout: 60

    - name: Reset root password and allow remote access
      ansible.builtin.shell: |
        mysql -S /var/run/mysqld/mysqld.sock <<EOF
        FLUSH PRIVILEGES;
        ALTER USER 'root'@'localhost'
        IDENTIFIED WITH mysql_native_password
        BY '{{ mysql_root_password }}';
        CREATE USER IF NOT EXISTS 'root'@'%'
        IDENTIFIED WITH mysql_native_password
        BY '{{ mysql_root_password }}';
        GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
        FLUSH PRIVILEGES;
        EOF

    - name: Stop MySQL safe mode
      ansible.builtin.shell: pkill mysqld
      ignore_errors: yes

    - name: Start MySQL normally
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

    - name: Allow remote connections
      ansible.builtin.lineinfile:
        path: /etc/my.cnf
        insertafter: '\[mysqld\]'
        line: 'bind-address=0.0.0.0'
        state: present

    - name: Restart MySQL
      ansible.builtin.service:
        name: mysqld
        state: restarted
