- name: Configure MySQL correctly on RHEL
  hosts: mysql
  become: yes

  vars:
    mysql_root_password: RoboShop@1

  tasks:
    - name: Install PyMySQL
      ansible.builtin.dnf:
        name: python3-PyMySQL
        state: present

    - name: Start MySQL
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

    - name: Ensure root password and privileges
      community.mysql.mysql_user:
        name: root
        host: localhost
        password: "{{ mysql_root_password }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
        priv: "*.*:ALL,GRANT"
        state: present

    - name: Allow root remote access
      community.mysql.mysql_user:
        name: root
        host: "%"
        password: "{{ mysql_root_password }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
        priv: "*.*:ALL,GRANT"
        state: present

    - name: Allow remote connections
      ansible.builtin.lineinfile:
        path: /etc/my.cnf
        insertafter: '\[mysqld\]'
        line: 'bind-address=0.0.0.0'

    - name: Restart MySQL
      ansible.builtin.service:
        name: mysqld
        state: restarted
