- name: Configure MySQL Component
  hosts: mysql
  become: yes

  tasks:
    - name: Remove MariaDB if present
      ansible.builtin.dnf:
        name: mariadb*
        state: absent
      ignore_errors: yes

    - name: Install MySQL repo
      ansible.builtin.dnf:
        name: https://repo.mysql.com/mysql80-community-release-el9-1.noarch.rpm
        state: present
        disable_gpg_check: yes

    - name: Import MySQL GPG key
      ansible.builtin.rpm_key:
        state: present
        key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2023

    - name: Install MySQL Server
      ansible.builtin.dnf:
        name: mysql-community-server
        state: present

    - name: Start and enable MySQL
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

    - name: Wait for MySQL to be ready
      ansible.builtin.wait_for:
        port: 3306
        delay: 5
        timeout: 60

    - name: Set MySQL root password
      ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1
      args:
        creates: /root/.my.cnf

    - name: Create MySQL root config
      ansible.builtin.copy:
        dest: /root/.my.cnf
        content: |
          [client]
          user=root
          password=RoboShop@1
        mode: '0600'

    - name: Configure MySQL root authentication and remote access
      ansible.builtin.shell: |
        mysql -uroot <<EOF
        ALTER USER 'root'@'localhost'
        IDENTIFIED WITH mysql_native_password
        BY 'RoboShop@1';
        CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'RoboShop@1';
        GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
        FLUSH PRIVILEGES;
        EOF


    - name: Configure MySQL bind address
      ansible.builtin.lineinfile:
        path: /etc/my.cnf
        regexp: '^bind-address'
        insertafter: '\[mysqld\]'
        line: 'bind-address=0.0.0.0'
      notify: Restart MySQL

  handlers:
    - name: Restart MySQL
      ansible.builtin.service:
        name: mysqld
        state: restarted
