- name: Configure MySQL Component (RHEL)
  hosts: mysql
  become: yes
  vars:
    mysql_root_password: RoboShop@1

  tasks:

    - name: Remove MariaDB if present
      ansible.builtin.dnf:
        name: mariadb*
        state: absent
      ignore_errors: yes

    - name: Install MySQL repo
      ansible.builtin.dnf:
        name: https://repo.mysql.com/mysql80-community-release-el9-1.noarch.rpm
        state: present
        disable_gpg_check: yes

    - name: Install MySQL server
      ansible.builtin.dnf:
        name: mysql-community-server
        state: present

    - name: Start MySQL
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

    - name: Set MySQL root password (socket auth)
      community.mysql.mysql_user:
        name: root
        host: localhost
        password: "{{ mysql_root_password }}"
        login_unix_socket: /var/lib/mysql/mysql.sock
        check_implicit_admin: yes
        priv: "*.*:ALL,GRANT"
        state: present

    - name: Allow root remote access
      community.mysql.mysql_user:
        name: root
        host: "%"
        password: "{{ mysql_root_password }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
        priv: "*.*:ALL,GRANT"
        state: present

    - name: Allow MySQL remote connections
      ansible.builtin.lineinfile:
        path: /etc/my.cnf
        insertafter: '\[mysqld\]'
        line: 'bind-address=0.0.0.0'
        state: present

    - name: Restart MySQL
      ansible.builtin.service:
        name: mysqld
        state: restarted
