- name: Configure MySQL Component (RHEL / MySQL 8)
  hosts: mysql
  become: yes

  tasks:

    - name: Stop MySQL if running
      ansible.builtin.service:
        name: mysqld
        state: stopped
      ignore_errors: yes

    - name: Remove MariaDB if present
      ansible.builtin.dnf:
        name: mariadb*
        state: absent
      ignore_errors: yes

    - name: Install MySQL repo
      ansible.builtin.dnf:
        name: https://repo.mysql.com/mysql80-community-release-el9-1.noarch.rpm
        state: present
        disable_gpg_check: yes

    - name: Install MySQL Server
      ansible.builtin.dnf:
        name: mysql-community-server
        state: present

    - name: Start MySQL normally
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

    - name: Stop MySQL to reset root password
      ansible.builtin.service:
        name: mysqld
        state: stopped

    - name: Start MySQL with skip-grant-tables
      ansible.builtin.shell: |
        mysqld_safe --skip-grant-tables --skip-networking &
      async: 0
      poll: 0

    - name: Wait for MySQL (skip-grant-tables)
      ansible.builtin.pause:
        seconds: 5

    - name: Reset root password and allow remote access
      ansible.builtin.shell: |
        mysql <<EO
