- name: Reset MySQL root and enable remote access (RHEL)
  hosts: mysql
  become: yes

  vars:
    mysql_root_password: RoboShop@1

  tasks:

    - name: Install PyMySQL
      ansible.builtin.dnf:
        name: python3-PyMySQL
        state: present

    - name: Stop MySQL
      ansible.builtin.service:
        name: mysqld
        state: stopped

    - name: Start MySQL with skip grant tables
      ansible.builtin.shell: |
        mysqld_safe --skip-grant-tables --skip-networking &
      async: 30
      poll: 0

    - name: Wait for MySQL socket
      ansible.builtin.wait_for:
        path: /var/lib/mysql/mysql.sock
        timeout: 30

    - name: Reset root authentication and password
      ansible.builtin.shell: |
        mysql <<EOF
        FLUSH PRIVILEGES;
        ALTER USER 'root'@'localhost'
        IDENTIFIED WITH mysql_native_password
        BY '{{ mysql_root_password }}';
        CREATE USER IF NOT EXISTS 'root'@'%'
        IDENTIFIED WITH mysql_native_password
        BY '{{ mysql_root_password }}';
        GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
        FLUSH PRIVILEGES;
        EOF

    - name: Stop MySQL (safe mode)
      ansible.builtin.service:
        name: mysqld
        state: stopped

    - name: Start MySQL normally
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

    - name: Allow remote MySQL connections
      ansible.builtin.lineinfile:
        path: /etc/my.cnf
        insertafter: '\[mysqld\]'
        line: 'bind-address=0.0.0.0'
        state: present

    - name: Restart MySQL
      ansible.builtin.service:
        name: mysqld
        state: restarted
