- name: Remove catalogue service
  hosts: catalogue
  become: yes
  tasks:

    - name: Stop catalogue service
      ansible.builtin.service:
        name: catalogue
        state: stopped
      ignore_errors: yes

    - name: Disable catalogue service
      ansible.builtin.service:
        name: catalogue
        enabled: no
      ignore_errors: yes

    - name: Remove systemd service file
      ansible.builtin.file:
        path: /etc/systemd/system/catalogue.service
        state: absent

    - name: Reload systemd
      ansible.builtin.command: systemctl daemon-reload

    - name: Remove application directory
      ansible.builtin.file:
        path: /app
        state: absent

    - name: Remove catalogue user
      ansible.builtin.user:
        name: catalogue
        state: absent
